/* config.h.  Generated by configure.  */
/* config.h.in.  Generated automatically from configure.in by autoheader.  */

/* Define to empty if the keyword does not work.  */
/* #undef const */

/* Define as __inline if that's what the C compiler calls it.  */
/* #undef inline */

/* Define if you have the ANSI C header files.  */
#define STDC_HEADERS 1

/* Define if you have the gettimeofday function.  */
/* #undef HAVE_GETTIMEOFDAY */

/* Define if you have the <arpa/inet.h> header file.  */
#define HAVE_ARPA_INET_H 1

/* Define if you have the <fcntl.h> header file.  */
/* #undef HAVE_FCNTL_H */

/* Define if you have the <netinet/in.h> header file.  */
#define HAVE_NETINET_IN_H 1

/* Define if you have the <netinet/ip.h> header file.  */
#define HAVE_NETINET_IP_H 1

/* Define if you have the <netinet/tcp.h> header file.  */
#define HAVE_NETINET_TCP_H 1

/* Define if you have the <netinet/in_systm.h> header file.  */
#define HAVE_NETINET_IN_SYSTM_H 1

/* Define if you have the <netdb.h> header file.  */
#define HAVE_NETDB_H 1

/* Define if you have the <sched.h> header file.  */
#define HAVE_SCHED_H 1

/* Define if you have the <sys/resource.h> header file.  */
#define HAVE_SYS_RESOURCE_H 1

/* Define if you have the <sys/time.h> header file.  */
/* #undef HAVE_SYS_TIME_H */

/* Define if you have the <sys/sockio.h> header file.  */
/* #undef HAVE_SYS_SOCKIO_H */

/* Define if you have the <linux/if_tun.h> header file.  */
#define HAVE_LINUX_IF_TUN_H 1

/* Define if you have setproctitle. */
/* #undef HAVE_SETPROC_TITLE */

/* #undef HAVE_LIBUTIL_H */

/* Define if you have ZLIB */
#define HAVE_ZLIB 1

/* Define if you have LZO */
#define HAVE_LZO 1

/* Define if you have OpenSSL */
/* #undef HAVE_SSL */

/* #undef HAVE_SSL_BLOWFISH */

/* #undef HAVE_SSL_AES */

/* #undef HAVE_SSL_EVP */

/* #undef HAVE_SHAPER */

#define ENABLE_NAT_HACK 1

/* Release version and date */
#define VTUN_VER "3.X 05/17/2017"
